package com.paathshala.flight.flightservice.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Flight")
public class Flight {
	private String id;
	private int flightId;
	private String airlinesName;
	private String destinationName;
	private String boardingName;

	public Flight() {
	}

	public Flight(int flightId, String airlinesName, String destinationName, String boardingName) {
		this.flightId = flightId;
		this.airlinesName = airlinesName;
		this.destinationName = destinationName;
		this.boardingName = boardingName;
	}

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	@DynamoDBAttribute
	public int getFlightId() {
		return flightId;
	}

	public void setFlightId(int flightId) {
		this.flightId = flightId;
	}

	@DynamoDBAttribute
	public String getAirlinesName() {
		return airlinesName;
	}

	public void setAirlinesName(String airlinesName) {
		this.airlinesName = airlinesName;
	}

	@DynamoDBAttribute
	public String getDestinationName() {
		return destinationName;
	}

	public void setDestinationName(String destinationName) {
		this.destinationName = destinationName;
	}

	@DynamoDBAttribute
	public String getBoardingName() {
		return boardingName;
	}

	public void setBoardingName(String boardingName) {
		this.boardingName = boardingName;
	}

	public void setId(String id) {
		this.id = id;
	}
}
